general {
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 5
    on-timeout = if pgrep -x "hyprlock"; then echo "LOCKED - Turning OFF" >> /tmp/hypridle.log; hyprctl dispatch dpms off; else echo "UNLOCKED - Ignoring" >> /tmp/hypridle.log; fi
    on-resume = echo "RESUME - Turning ON" >> /tmp/hypridle.log; hyprctl dispatch dpms on
}
