#!/usr/bin/env bash

# dev-env - Automate the custom builds
#
# Usage:
# just run it


SRCS="${HOME}/src/upstream"
echo "[DEV] This script requires sudo priveleges:"
sudo -v


################################################################################
################################# N E O V I M ##################################
################################################################################

NEOVIM_VERSION="v0.11.5"
TREESITTER_VERSION="v0.10.0"

build_neovim() {
    # source
    if [[ -d "${SRCS}/nvim-treesitter" ]]; then
        pushd "${SRCS}/nvim-treesitter"
        git fetch
    else
        echo "[DEV] Treesitter is not cloned. Cloning..."
        pushd "${SRCS}"
        git clone git@github.com:nvim-treesitter/nvim-treesitter.git
        popd
        pushd "${SRCS}/nvim-treesitter"
    fi
    git checkout "$TREESITTER_VERSION"
    popd

    if [[ ! -d "${SRCS}/neovim" ]]; then
        echo "[DEV] Neovim is not cloned. Cloning..."
        pushd "$SRCS"
        git clone git@github.com:neovim/neovim.git
        popd
        pushd "${SRCS}/neovim"
    else
        pushd "${SRCS}/neovim"
        git fetch
    fi
    git checkout "$NEOVIM_VERSION"

    # dependencies
    sudo pacman -S base-devel cmake ninja curl git --noconfirm

    # build
    git clean -dfx 
    make distclean 2>/dev/null || true
    make CMAKE_BUILD_TYPE=RelWithDebInfo
    sudo make install

    popd
}


################################################################################
################################### T M U X ####################################
################################################################################

TMUX_VERSION="3.6a"
TPM_VERSION="v3.1.0"

build_tmux() {
    # source
    if [[ ! -d "${XDG_CONFIG_HOME}/tmux/plugins/tpm" ]]; then
        pushd "${XDG_CONFIG_HOME}/tmux/plugins/"
        git clone git@github:tmux-plugins/tpm.git
    else
        pushd "${XDG_CONFIG_HOME}/tmux/plugins/tpm"
        git fetch
    fi
    git checkout "$TPM_VERSION"
    popd

    if [[ ! -d "${SRCS}/tmux" ]]; then
        echo "[DEV] Tmux is not cloned. Cloning..."
        pushd "$SRCS"
        git clone git@github.com:tmux/tmux.git
        popd
        pushd "${SRCS}/tmux"
    else
        pushd "${SRCS}/tmux"
        git fetch
    fi
    git checkout "$TMUX_VERSION"

    # dependencies
    sudo pacman -S libevent ncurses gcc automake autoconf pkg-config --noconfirm
    sudo pacman -S bison libutempter --noconfirm

    # build
    git clean -dfx
    sh autogen.sh
    ./configure && make
    sudo make install

    popd
}


################################################################################
############################# A L A C R I T T Y ################################
################################################################################

ALACRITTY_VERSION="v0.16.1"

build_alacritty() {
    # source
    if [[ ! -d "${SRCS}/alacritty" ]]; then
        echo "[DEV] Alacritty is not cloned. Cloning..."
        pushd "$SRCS"
        git clone git@github.com:alacritty/alacritty.git
        popd
        pushd "${SRCS}/alacritty"
    else
        pushd "${SRCS}/alacritty"
        git fetch
    fi
    git checkout "$ALACRITTY_VERSION"

    # dependencies
    sudo pacman -S rust cmake freetype2 fontconfig pkg-config make --noconfirm
    sudo pacman -S libxcb libxkbcommon python --noconfirm

    # build
    cargo clean
    cargo build --release --no-default-features --features=wayland

    # Install new binary (creates a NEW inode)
    sudo install -m 755 target/release/alacritty /usr/local/bin/alacritty

    sudo cp extra/logo/alacritty-term.svg /usr/share/pixmaps/Alacritty.svg
    sudo desktop-file-install extra/linux/Alacritty.desktop
    sudo update-desktop-database

    popd
}


program="$1"
while [[ $# -gt 0 ]]; do
    echo "ARG: \"$1\""
    case $program in
        "neovim")
            build_neovim
            shift
            program="$1"
            ;;
        "tmux")
            build_tmux
            shift
            program="$1"
            ;;
        "alacritty")
            build_alacritty
            shift
            program="$1"
            ;;
        "-a")
            build_neovim
            build_tmux
            build_alacritty
            exit 0
            ;;
        *)
            echo "[DEV] Unknown option '$program'. Skipping"
            shift
            program="$1"
            ;;
    esac
done
