#!/usr/bin/env bash

# dev-env - Automate the custom builds
#
# Usage:
# just run it


SRCS="${HOME}/src/upstream"
echo "[DEV] This script requires sudo priveleges:"
sudo -v


################################################################################
################################# N E O V I M ##################################
################################################################################

NEOVIM_VERSION="v0.11.5"

build_neovim() {
    # source
    if [[ ! -d "${SRCS}/neovim" ]]; then
        echo "[DEV] Neovim is not cloned. Cloning..."
        pushd "$SRCS"
        git clone git@github.com:neovim/neovim.git
        popd
        pushd "${SRCS}/neovim"
    else
        pushd "${SRCS}/neovim"
        git fetch
    fi
    git checkout "$NEOVIM_VERSION"

    # dependencies
    sudo pacman -S base-devel cmake ninja curl git --noconfirm

    # build
    git clean -dfx 
    make distclean 2>/dev/null || true
    make CMAKE_BUILD_TYPE=RelWithDebInfo
    sudo make install

    popd
}


################################################################################
################################### T M U X ####################################
################################################################################

TMUX_VERSION="3.6a"
TPM_VERSION="v3.1.0"

build_tmux() {
    # source
    if [[ ! -d "${XDG_CONFIG_HOME}/tmux/plugins/tpm" ]]; then
        pushd "${XDG_CONFIG_HOME}/tmux/plugins/"
        git clone git@github:tmux-plugins/tpm.git
        popd
    else
        pushd "${XDG_CONFIG_HOME}/tmux/plugins/tpm"
        git fetch
        popd
    fi
    git checkout "$TPM_VERSION"

    if [[ ! -d "${SRCS}/tmux" ]]; then
        echo "[DEV] Tmux is not cloned. Cloning..."
        pushd "$SRCS"
        git clone git@github.com:tmux/tmux.git
        popd
        pushd "${SRCS}/tmux"
    else
        pushd "${SRCS}/tmux"
        git fetch
    fi
    git checkout "$TMUX_VERSION"

    # dependencies
    sudo pacman -S libevent ncurses gcc automake autoconf pkg-config --noconfirm
    sudo pacman -S bison libutempter --noconfirm

    # build
    git clean -dfx
    sh autogen.sh
    ./configure && make
    sudo make install

    popd
}

################################################################################
############################# A L A C R I T T Y ################################
################################################################################

ALACRITTY_VERSION="v0.16.1"

build_alacritty() {
    # source
    if [[ ! -d "${SRCS}/alacritty" ]]; then
        echo "[DEV] Alacritty is not cloned. Cloning..."
        pushd "$SRCS"
        git clone git@github.com:alacritty/alacritty.git
        popd
        pushd "${SRCS}/alacritty"
    else
        pushd "${SRCS}/alacritty"
        git fetch
    fi
    git checkout "$ALACRITTY_VERSION"

    # dependencies
    sudo pacman -S rust cmake freetype2 fontconfig pkg-config make --noconfirm
    sudo pacman -S libxcb libxkbcommon python --noconfirm

    # build
    cargo clean
    cargo build --release --no-default-features --features=wayland

    # Install new binary (creates a NEW inode)
    sudo install -m 755 target/release/alacritty /usr/local/bin/alacritty

    sudo cp extra/logo/alacritty-term.svg /usr/share/pixmaps/Alacritty.svg
    sudo desktop-file-install extra/linux/Alacritty.desktop
    sudo update-desktop-database

    popd
}

program="$1"
while [[ $# -gt 0 ]]; do
    echo "ARG: \"$1\""
    case $program in
        "neovim")
            build_neovim
            shift
            program="$1"
            ;;
        "tmux")
            build_tmux
            shift
            program="$1"
            ;;
        "alacritty")
            build_alacritty
            shift
            program="$1"
            ;;
        "-a")
            build_neovim
            build_tmux
            build_alacritty
            exit 0
            ;;
        *)
            echo "[DEV] Unknown option '$program'. Skipping"
            shift
            program="$1"
            ;;
    esac
done

usage() {
    echo -e "${CLR_YLW}${0}- A script that will only work for me lol"
    echo -e "${CLR_MGA}usage: ./run [--sim] PROGRAM"
    echo -e ''
    echo -e "${CLR_RED}[IMPORTANT] This script does not support multiple PROGRAM arguments."
    # echo -e "${CLR_RST}"
    echo -e "${CLR_GRN}"
    echo -e 'Examples:'
    echo -e './run --sim nvim'
    echo -e './run tmux'
    echo -e "${CLR_RST}"
    echo -e ''
}

# safety check for argument count
if [[ $# -gt 2 ]]; then
    echo -e "${CLR_RED}"
    echo -e '[ERROR] Too many arguments.'
    echo -e "${CLR_RST}"
    usage
    exit 1
fi

# check for sim run, and also gets the name of the run
while [[ $# -gt 0 ]]; do
    echo "[RUN] arg: ${1}"
    if [[ $ARG1 == "--sim" ]]; then
        SIM="1"
    else
        ARG2="$1"
    fi
    shift
done

# basic log functionality
log() {
    if [[ $SIM == "1" ]]; then
        echo "[SIM]: $1"
    else
        echo "$1"
    fi
}

log "[RUN] env: ${DEV_ENV} -- program: ${ARG2}"

RUNS_DIR=`find $DEV_ENV/runs -mindepth 1 -maxdepth 1 -executable`

for RUN in $RUNS_DIR; do
    if basename $RUN | grep -vq "$ARG2"; then
        log "[RUN] arg ${ARG2} filtered out $RUN"
        continue
    fi

    log "[RUN] Running Script: ${RUN}"

    if [[ $SIM == "0" ]]; then
        $RUN
    fi
done
