FROM ubuntu:24.04

RUN apt-get update && apt-get install -y \
    sudo \
    build-essential \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN useradd -ms /bin/bash jaysh && \
    echo "jaysh:testpasswd" | chpasswd && \
    usermod -aG sudo jaysh

WORKDIR /home/jaysh

RUN git clone https://github.com/jayshozie/dotfiles.git

WORKDIR /home/jaysh/dotfiles

RUN git checkout dev
