#!/usr/bin/env bash

# Usage:
# ./run [-dry|--dry-run]
#
# Options:
#    -dry : only test the config, don't actually do anything.

export DEV_ENV=$(cd "$(dirname "$0")" && pwd)
dry_run="0"

if [[ -v XDG_CONFIG_HOME ]]; then
    echo "[RUN] XDG_CONFIG_HOME is set."
    echo "[RUN] It has the value : $XDG_CONFIG_HOME"
else
    echo "[RUN] XDG_CONFIG_HOME is not set."
    echo "[RUN] Using ${HOME}/.config for it."
    export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
fi

SRC="${DEV_ENV}/modules/"
DEST=""

pushd "$DEV_ENV"

modules=`find modules/* -maxdepth 0`

if [[ $1 == "-dry" ]]; then
    dry_run="1"
fi
if [[ $1 == "--dry-run" ]]; then
    dry_run="1"
fi

log() {
    if [[ $dry_run == "0" ]]; then
        echo "$1"
    else
        echo "[DRY]: $1"
    fi
}

for m in $modules; do
    log "[RUN] "
    if [[ -f "${m}/.sudo" ]]; then
        log "[RUN] Module $m requires sudo access."
        sudo -v
    fi
    if [[ ! -f "${m}/.dest" ]]; then
        log "[RUN/ERROR] Module $m doesn't have a .dest file. Skipping..."
        continue
    else
        DEST=$(envsubst < "${m}/.dest")
        log "[RUN] Removing ${DEST}..."
        if [[ $dry_run == "0" ]]; then
            rm -rf "$DEST"
        else
            log "rm -rf $DEST"
        fi

        log "[RUN] Copying ${m}/payload to ${DEST}..."
        if [[ $dry_run == "0" ]]; then
            cp -r "${m}/payload" "$DEST"
        else
            log "cp -r ${m}/payload ${DEST}"
        fi
    fi
done


popd # $DEV_ENV
