#!/usr/bin/env bash
# WARNING: DO NOT RUN MORE THAN ONCE IT WILL REMOVE YOUR EXISTING CONFIG FILES
#          AND CREATES EXTRA COPIES OF YOUR CONFIG FILES

# Debian-based Distros' Post-Installation Script

# make sure everything is up-to-date
sudo apt update -y
sudo apt upgrade -y

# make sure everything is installed except neovim
#
# don't you just love github, it takes 4 words to install git, and 90 for gh-cli
(type -p wget >/dev/null || (sudo apt update && sudo apt install wget -y)) \
	&& sudo mkdir -p -m 755 /etc/apt/keyrings \
	&& out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg \
	&& cat $out | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
	&& sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
	&& sudo mkdir -p -m 755 /etc/apt/sources.list.d \
	&& echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
	&& sudo apt update \
	&& sudo apt install -y gh git make stow gpg

# check default config files, back them up and remove them.
if [[ $? -eq 0 ]]; then
    # bash
    if [[ -f $HOME/.bashrc ]]; then
        mv $HOME/.bashrc $HOME/.bashrc.bak
        echo "[INFO] Default .bashrc moved to $HOME/.bashrc.bak"
    fi
    if [[ -f $HOME/.bash_aliases ]]; then
        mv $HOME/.bash_aliases $HOME/.bash_aliases.bak
        echo "[INFO] Default .bash_aliases moved to $HOME/.bash_aliases.bak"
    fi

    # git
    if [[ -f $HOME/.gitconfig ]]; then
        mv $HOME/.gitconfig $HOME/.gitconfig.bak
        echo "[INFO] Default .gitconfig moved to $HOME/.gitconfig.bak"
    fi

    # neovim
    if [[ -d $HOME/.config/nvim ]]; then
        mv $HOME/.config/nvim $HOME/nvim.bak
        echo "[INFO] Default .config/nvim moved to $HOME/nvim.bak"
    fi

    # alacritty
    if [[ -d $HOME/.config/alacritty ]]; then
        mv $HOME/.config/alacritty $HOME/alacritty.bak
        echo "[INFO] Default .config/alacritty moved to $HOME/alacritty.bak"
    fi

    # tmux
    if [[ -d $HOME/.tmux.conf ]]; then
        mv $HOME/.tmux.conf $HOME/.tmux.conf.bak
        echo "[INFO] Default .tmux.conf moved to $HOME/.tmux.conf.bak"
    fi
    if [[ -d $HOME/.config/tmux ]]; then
        mv $HOME/.config/tmux $HOME/tmux.bak
        echo "[INFO] Default .config/tmux moved to $HOME/tmux.bak"
    fi

    # CLONES_DIR
    CLONES_DIR=${HOME}/clones
    mkdir -p $HOME/clones
else
    echo "[ERROR] Something went wrong with the installation of the programs."
    echo "[INFO] Please check the installation, then re-run this script."
fi

./run bash
source $HOME/.bash_env
./run dev
./run git
./run alacritty
./run tmux
./run neovim
./run autostart
./run scripts
