#!/usr/bin/env bash

log() {
    if [[ dry_run -eq 1 ]]; then
        printf "$timestamp [DRY]: $1\n" 2>&1
    else
        printf "$timestamp $1\n" 2>&1 | tee --append ${HOME}/arise.log
    fi
}

main() {
    dry_run=0

    if [[ $1 == "--dry-run" ]]; then
        dry_run=1
    fi

    log_file="${HOME}/arise.log"

    if [[ ! -f $log_file ]]; then
        touch $log_file
    fi

    timestamp=$(date '+%Y/%m/%d %H:%M:%S')
    declare -A pids

    pids[nvim]=$(pgrep nvim -d ' ')
    pids[harper-ls]=$(pgrep harper-ls -d ' ')
    pids[librewolf]=$(pgrep librewolf -d ' ')
    pids[spotify]=$(pgrep spotify -d ' ')
    pids[jellyfin-deskto]=$(pgrep jellyfin-deskto -d ' ')

    status=0
    for p in "${!pids[@]}"; do
        if [[ "${pids[$p]}" == '' ]]; then
            log "[DIE] $p is not running."
            continue
        fi
        log "[DIE] SIGKILL $p --> ${pids[$p]}"
        if [[ dry_run -eq 1 ]]; then
            log "kill -9 ${pids[$p]}"
        else
            kill -9 ${pids[$p]}
        fi

        # if [[ dry_run -ne 1 && ! $(pgrep $p) ]]; then
        #     log "[DIE] Killed $p"
        # else
        #     log "[DIE] Couldn't kill ${p}."
        #     status=1
        # fi
    done

    if [[ status -ne 0 ]]; then
        log "[DIE] Couldn't kill all."
        log "[DIE] Please manually kill them, and then re-run the script."
    else
        log "[DIE] Killed everything successfully."
        log "[DIE] Rebooting ..."
        if [[ dry_run -eq 1 ]]; then
            log "shutdown -r now"
        else
            shutdown -r now
        fi
    fi
}

main "$@"
