#!/usr/bin/env bash

# rm -rf the default configs
rm -rf $XDG_CONFIG_HOME/alacritty
# pushd to env
pushd $DEV_ENV/env
# stow the alacritty package
stow --target=$HOME alacritty
# go back to wherever you were
popd
