#!/usr/bin/env bash

CLR_RED='\033[0;31m'
CLR_WHT='\033[0;37m'
CLR_RST='\033[0m'

# rm -rf the default
if [[ -d $XDG_CONFIG_HOME/autostart ]]; then
    echo -e "${CLR_RED}"
    echo -e "[RUNS/AUTOSTART] WARNING : $XDG_CONFIG_HOME/autostart EXISTS."
    echo -e "[RUNS/AUTOSTART] THIS WILL REMOVE THE FILES IN IT."
    read -r "[RUNS/AUTOSTART] DID YOU BACK THEM UP? (y/N)" answer
    if [[ $answer == "y" ]]; then
        echo -e "${CLR_RST}[RUNS/AUTOSTART] Good for you."
        sleep 2
    else
        echo -e "${CLR_RED}[RUNS/AUTOSTART] GO BACK THEM UP AND RE-RUN THIS SCRIPT."
        exit 1
    fi
fi
rm -rf $XDG_CONFIG_HOME/autostart

pushd $DEV_ENV/env

stow --target=$HOME autostart

popd
