#!/usr/bin/env bash

CLR_RED='\033[0;31m'
CLR_WHT='\033[0;37m'
CLR_RST='\033[0m'

# rm- rf the default configs
rm -rf $HOME/.bashrc $HOME/.bash_env $HOME/.bash_aliases
# pushd to env
pushd $DEV_ENV/env
# stow the bash package
stow --target=$HOME bash
# go back to wherever you were
popd

echo -e "${CLR_RED}[RUNS/BASH] IMPORTANT : DON'T FORGET TO SOURCE BASHRC"
