#!/usr/bin/env bash

CLR_RED='\033[0;31m'
CLR_WHT='\033[0;37m'
CLR_RST='\033[0m'

# WARNING
# echo "[RUNS/${SCRIPT}] ${CLR_RED}WARNING${CLR_RST} : ${1} SHOULD BE RUN AFTER ${DEV_ENV}/ubuntu-install"

if [[ ! -d $CLONES_DIR ]]; then
    echo -e "[RUNS/DEV] ${CLR_RED}ERROR${CLR_RST} : ${0} SHOULD BE RUN AFTER THE POST-INSTALL SCRIPTS"
    exit 1
fi

sudo apt -y update
sudo apt -y upgrade

################################################################################
################################# N E O V I M ##################################
################################################################################

NEOVIM_VERSION="v0.11.5"

# get dependencies
sudo apt-get -y install ninja-build gettext cmake curl build-essential git

# build neovim
if [[ -d $CLONES_DIR/neovim ]]; then
    pushd $CLONES_DIR/neovim
    git fetch
else
    pushd $CLONES_DIR
    git clone git@github.com:neovim/neovim.git
    popd
    pushd $CLONES_DIR/neovim
fi

# update this regularly
git checkout "$NEOVIM_VERSION"

if [[ $(nvim --version | grep $NEOVIM_VERSION) ]]; then
    VER_SAME=true
else
    VER_SAME=false
fi

if [[ $VER_SAME == true ]]; then
    echo -e "${CLR_RED}"
    echo "[RUNS/DEV] neovim version $NEOVIM_VERSION exists, and built before."
    echo "[RUNS/DEV] Skipping neovim."
    echo -e "${CLR_RST}"
else
    rm -rf build
    make CMAKE_BUILD_TYPE=RelWithDebInfo
    sudo make install
fi
popd

################################################################################
################################### T M U X ####################################
################################################################################

TMUX_VERSION="3.6a"

# get dependencies
sudo apt-get -y install libevent-dev ncurses-dev bison autoconf automake pkg-config

# build tmux
if [[ -d $CLONES_DIR/tmux ]]; then
    pushd $CLONES_DIR/tmux
    git fetch
else
    pushd $CLONES_DIR
    git clone git@github.com:tmux/tmux.git
    popd
    pushd $CLONES_DIR/tmux
fi

# update this regularly
git checkout "$TMUX_VERSION"

if [[ $(tmux -V | grep $TMUX_VERSION) ]]; then
    VER_SAME=true
else
    VER_SAME=false
fi

if [[ $VER_SAME == true ]]; then
    echo -e "${CLR_RED}"
    echo "[RUNS/DEV] tmux version $TMUX_VERSION exists, and built before."
    echo "[RUNS/DEV] Skipping tmux."
    echo -e "${CLR_RST}"
else
    if [[ -f Makefile ]]; then
        make distclean
    fi
    sh autogen.sh
    ./configure && make
    [ -f /usr/local/bin/tmux ] && sudo rm /usr/local/bin/tmux
    sudo make install
fi
popd

################################################################################
############################# A L A C R I T T Y ################################
################################################################################

ALACRITTY_VERSION="0.16.1"

# get dependencies
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
rustup override set stable
rustup update stable
sudo apt-get -y install cmake g++ pkg-config libfontconfig1-dev libxcb-xfixes0-dev libxkbcommon-dev python3

if [[ -d $CLONES_DIR/alacritty ]]; then
    pushd $CLONES_DIR/alacritty
    git fetch
else
    pushd $CLONES_DIR
    git clone git@github.com:alacritty/alacritty.git
    popd
    pushd $CLONES_DIR/alacritty
fi

# they use 0.16.1 for --version but v0.16.1 for tags, weird.
# this works, for example string becomes v0.16.1
git checkout v"${ALACRITTY_VERSION}"

if [[ $(alacritty --version | grep $ALACRITTY_VERSION) ]]; then
    VER_SAME=true
else
    VER_SAME=false
fi

if [[ $VER_SAME == true ]]; then
    echo -e "${CLR_RED}"
    echo "[RUNS/DEV] Alacritty version $ALACRITTY_VERSION exists, and built before."
    echo "[RUNS/DEV] Skipping Alacritty."
    echo -e "${CLR_RST}"
else
    cargo clean
    cargo build --release

    sudo install -m 755 target/release/alacritty /usr/local/bin/alacritty
    sudo chmod +x /usr/local/bin/alacritty

    sudo cp extra/logo/alacritty-term.svg /usr/share/pixmaps/Alacritty.svg
    sudo desktop-file-install extra/linux/Alacritty.desktop
    sudo update-desktop-database
fi
popd
