#!/usr/bin/env bash

CLR_RED='\033[0;31m'
CLR_WHT='\033[0;37m'
CLR_RST='\033[0m'

# WARNING
# echo "[RUNS/${SCRIPT}] ${CLR_RED}WARNING${CLR_RST} : ${1} SHOULD BE RUN AFTER ${DEV_ENV}/ubuntu-install"

if [[ ! -d $CLONES_DIR ]]; then
    echo -e "[RUNS/DEV] ${CLR_RED}ERROR${CLR_RST} : ${0} SHOULD BE RUN AFTER THE POST-INTSALL SCRIPTS"
    exit 1
fi

sudo apt -y update
sudo apt -y upgrade

################################################################################
################################# N E O V I M ##################################
################################################################################

# get dependencies
sudo apt-get -y install ninja-build gettext cmake curl build-essential git

# build neovim
if [[ -d $CLONES_DIR/neovim ]]; then
    pushd $CLONES_DIR/neovim
    git fetch
else
    pushd $CLONES_DIR
    git clone git@github.com:neovim/neovim.git
    popd
    pushd $CLONES_DIR/neovim
fi

# update this regularly
git checkout v0.11.5

rm -rf build
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install
popd

################################################################################
################################### T M U X ####################################
################################################################################

# get dependencies
sudo apt-get -y install libevent-dev ncurses-dev bison autoconf automake pkg-config

# build tmux
if [[ -d $CLONES_DIR/tmux ]]; then
    pushd $CLONES_DIR/tmux
    git fetch
else
    pushd $CLONES_DIR
    git clone git@github.com:tmux/tmux.git
    popd
    pushd $CLONES_DIR/tmux
fi

# update this regularly
git checkout 3.6a

if [[ -f Makefile ]]; then
    make distclean
fi

sh autogen.sh
./configure && make
[ -f /usr/local/bin/tmux ] && sudo rm /usr/local/bin/tmux
sudo make install
popd

################################################################################
############################# A L A C R I T T Y ################################
################################################################################

# get dependencies
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
rustup override set stable
rustup update stable
sudo apt-get -y install cmake g++ pkg-config libfontconfig1-dev libxcb-xfixes0-dev libxkbcommon-dev python3

if [[ -d $CLONES_DIR/alacritty ]]; then
    pushd $CLONES_DIR/alacritty
    git fetch
else
    pushd $CLONES_DIR
    git clone git@github.com:alacritty/alacritty.git
    popd
    pushd $CLONES_DIR/alacritty
fi

# update this regularly
git checkout v0.16.1

cargo clean
cargo build --release

sudo install -m 755 target/release/alacritty /usr/local/bin/alacritty
sudo chmod +x /usr/local/bin/alacritty

sudo cp extra/logo/alacritty-term.svg /usr/share/pixmaps/Alacritty.svg
sudo desktop-file-install extra/linux/Alacritty.desktop
sudo update-desktop-database
popd
