#!/usr/bin/env bash

# rm -rf the default configs
rm -rf "${XDG_CONFIG_HOME}/nvim"
# pushd to env
pushd "${DEV_ENV}/env" || exit 1
# stow the neovim package
stow --target="$HOME" neovim
# go back to wherever you were
popd
