#!/usr/bin/env bash

SESSIONIZER_LOC="${HOME}/src/upstream/tmux-sessionizer/tmux-sessionizer"
SYMLINK_LOC="${DEV_ENV}/env/scripts/tmux-sessionizer"
SCRIPTS_DIR="${HOME}/.local/bin/scripts"

# rm -rf the default configs
if [[ -d "$SCRIPTS_DIR" ]]; then
    cp -r -L "$SCRIPTS_DIR" "${HOME}/scripts.bak"
    rm -rf "$SCRIPTS_DIR"
else
    mkdir -p "$SCRIPTS_DIR"
fi

# symlink tmux-sessionizer
ln -s "$SESSIONIZER_LOC" "$SYMLINK_LOC"

# pushd to env
pushd "${DEV_ENV}/env" || exit 1
if [[ ! -d "${XDG_CONFIG_HOME}/tmux-sessionizer" ]]; then
    mkdir -p "${XDG_CONFIG_HOME}/tmux-sessionizer"
fi
if [[ ! -f "${XDG_CONFIG_HOME}/tmux-sessionizer/tmux-sessionizer.conf" ]]; then
    touch "${XDG_CONFIG_HOME}/tmux-sessionizer/tmux-sessionizer.conf"
fi
# stow the scripts package
stow --target="$HOME" scripts
# go back to wherever you were
popd
