#!/usr/bin/env bash

# rm -rf the default configs
rm -rf "${XDG_CONFIG_HOME}/tmux"
# pushd to env
pushd "${DEV_ENV}/env" || exit 1
# stow the tmux package
stow --target="$HOME" tmux
# go back to wherever you were
popd
