[ids]
*

[main]
# 1. Make CapsLock great again
# Holds -> Control, Taps -> Escape
capslock = overload(control, esc)

# 2. Move the actual CapsLock toggle to the physical Escape key
# Since you rarely need to shout, putting it in the corner is perfect.
esc = capslock
